### ISSUE TITLE
Create rolling average of cases

### ISSUE THREAD

**Issue by cczarnuch** [Mac-AI/covid19-pytorch#35]

**Comment by cczarnuch** [comment]
Inputs: dictionary created from process_csv() function in app.py. (You will need to put the csv file in the folder manually) [link](https://data.ontario.ca/dataset/f4112442-bdc8-45d2-be3c-12efae72fb27/resource/455fd63b-603d-4608-8216-7d8647f43350/download/conposcovidloc.csv)
Outputs: 7-day moving average of cases on per-day basis. Stored in the same format as the input dict.

For now just create the function, once we get the heatmap data linked with the raw case data we can add the data generated by this function(s) to the heatmap or other visualizations.

**Comment by jaymody** [comment]
@cczarnuch Finished the rolling mean code. Where do you want me to commit the code (ie in a separate file or in one of `predictions.py` or `preprocess.py`). I have code for the function, reproducing the below plot, and a unit test for the rolling ave function (I can put all those into a single file or we can separate it out into a tests folder, depends on what you want to do). Here's an example of the results using a 7 day window on the covid csv data:

![Screen Shot 2020-08-20 at 7 40 04 PM](https://user-images.githubusercontent.com/26451316/90836373-3589c700-e31d-11ea-84d0-8fed190f07cd.png)
